#! /usr/bin/env python
#  -*- coding: utf-8 -*-
 #
 # # Support module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Jul 30, 2019 02:08:48 PM UTC  platform: Windows NT
 
import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
 
def Annuler():
    print('unknown_support.Annuler')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import unknown
    unknown.vp_start_gui()
 
